from .lgsvl  import AwLgsvlSimulatorWidget
from .gazebo import AwGazeboSimulatorWidget
from .computing import AwComputingWidget
from .toggle_gateway import AwToggleGatewayWidget
from .load_computing_profile import AwLoadComputingProfileWidget
from .load_map_profile import AwLoadMapProfileWidget
from .load_map import AwLoadMapWidget
from .toggle_logging import AwToggleLoggingWidget
from .open_rviz import AwOpenRvizWidget
from .real import AwRealSensorWidget
from .rosbag import AwRosbagSimulatorWidget
from .sensor_source import AwSensorSourceWidget
from .sensor_source_select import AwSelectSensorSourceWidget
from .simulation import AwSimulationWidget